source: /

paths:
  static: public
  uploads: public/images

collection_groups:
  - heading: Content
    collections:
      - pages
      - blocks

collections_config:
  pages:
    path: src/content/pages
    url: /[full_slug]/
    icon: wysiwyg
    _enabled_editors:
      - visual
      - content
  articles:
    path: src/content/articles
    url: /articles/[full_slug]/
    icon: wysiwyg
    _enabled_editors:
      - visual
      - content
  events:
    path: src/content/events
    url: /events/[full_slug]/
    icon: wysiwyg
    _enabled_editors:
      - visual
      - content
  blogs:
    path: src/content/blogs
    url: /blogs/[full_slug]/
    icon: wysiwyg
    _enabled_editors:
      - visual
      - content

_snippets_imports:
  mdx: true
