source: /

paths:
  static: public
  uploads: public/images

collection_groups:
  - heading: Content
    collections:
      - pages
      - services
      - events
      - posts
      - articles
      - persons
      - policies

collections_config:
  pages:
    name: Pagina's
    path: src/content/pages
    url: /[full_slug]/
    icon: web
    disable_file_actions: true
    _enabled_editors:
      - visual
      - content
  services:
    name: Diensten
    path: src/content/services
    url: /services/[full_slug]/
    disable_file_actions: true
    disable_add_folder: true
    _enabled_editors:
      - content
      - visual
  articles:
    name: Artikelen
    path: src/content/articles
    icon: news
    disable_file_actions: true
    disable_add_folder: true
    _enabled_editors:
      - content
  events:
    name: Agenda
    path: src/content/events
    url: /events/[full_slug]/
    icon: calendar_month
    disable_file_actions: true
    disable_add_folder: true
    _enabled_editors:
      - content
  posts:
    name: Lezingen
    path: src/content/posts
    url: /posts/[full_slug]/
    icon: post
    disable_file_actions: true
    disable_add_folder: true
    _enabled_editors:
      - content
  persons:
    name: Personen
    path: src/content/persons
    url: /persons/[full_slug]/
    icon: person
    disable_file_actions: true
    disable_add_folder: true
  policies:
    name: Beleid
    path: src/content/policies
    url: /policies/[full_slug]/
    icon: policy
    disable_file_actions: true
    disable_add_folder: true
    _enabled_editors:
      - content
  reviews:
    name: Beoordelingen
    path: src/content/reviews.yml
    icon: star
    disable_file_actions: true
    disable_add_folder: true
    _enabled_editors:
      - data

data_config:
  reviews:
    path: src/content/reviews.yml

_inputs:
  block:
    hidden: true
  src:
    type: image
    options:
      accepts_mime_types: "image/jpeg,image/jpg,image/png,image/webp"
      mime_type: image/webp
      resize_style: contain
      width: 1920
      height: 1920
  href:
    type: url
  rating:
    type: range
    options:
      min: 0
      max: 5
      step: 0.5
  paragraph:
    type: textarea
  content:
    type: html
  reviews:
    type: multiselect
    options:
      values: _select_data.reviews
