source: /

paths:
  static: public
  uploads: public/images

collections_config:
  pages:
    name: Pagina's
    url: /[full_slug]/
    path: src/content/pages
    icon: web
    disable_file_actions: true
    disable_add_folder: true
  services:
    name: Aanbod
    url: /aanbod/[full_slug]/
    path: src/content/services
    icon: design_services
    disable_file_actions: true
    disable_add_folder: true
  articles:
    name: Artikelen
    url: /artikelen/[full_slug]/
    path: src/content/articles
    icon: news
    disable_file_actions: true
    disable_add_folder: true
  events:
    name: Agenda
    url: /agenda/[full_slug]/
    path: src/content/events
    icon: calendar_month
    disable_file_actions: true
    disable_add_folder: true
  posts:
    name: Lezingen
    url: /lezingen/[full_slug]/
    path: src/content/posts
    icon: post
    disable_file_actions: true
    disable_add_folder: true
  persons:
    name: Personen
    url: /personen/[full_slug]/
    path: src/content/persons
    icon: person
    disable_file_actions: true
    disable_add_folder: true
  policies:
    name: Beleid
    url: /beleid/[full_slug]/
    path: src/content/policies
    icon: policy
    disable_file_actions: true
    disable_add_folder: true
  reviews:
    name: Reviews
    url: /reviews/[full_slug]/
    path: src/content/reviews.yml
    icon: star
    disable_file_actions: true
    disable_add_folder: true
  data:
    name: Data
    path: src/data
    icon: data_object
    disable_file_actions: true
    disable_add_folder: true
    disable_add: true

collection_groups:
  - heading: Content
    collections:
      - pages
      - services
      - events
      - posts
      - persons
      - policies
      - reviews
  - heading: Settings
    collections:
      - data

_enabled_editors:
  - visual
  - content
  - data

_inputs:
  block:
    hidden: true
  src:
    type: image
    options:
      accepts_mime_types: "image/jpeg,image/jpg,image/png,image/webp"
      mime_type: image/webp
      resize_style: contain
      width: 1920
      height: 1920
  href:
    type: url
  rating:
    type: range
    options:
      min: 0
      max: 5
      step: 0.5
  paragraph:
    type: textarea
  content:
    type: html
  reviews:
    type: multiselect
    options:
      values: _select_data.reviews
