source: /

paths:
  static: public
  uploads: public/images

collection_groups:
  - heading: Content
    collections:
      - pages
      - articles
      - events
      - blogs
      - policies

collections_config:
  pages:
    path: src/content/pages
    url: /[full_slug]/
    icon: wysiwyg
    _enabled_editors:
      - visual
      - content
  articles:
    path: src/content/articles
    icon: wysiwyg
    _enabled_editors:
      - content
  events:
    path: src/content/events
    url: /events/[full_slug]/
    icon: wysiwyg
    _enabled_editors:
      - content
  blogs:
    path: src/content/blogs
    icon: wysiwyg
    _enabled_editors:
      - data
  policies:
    path: src/content/policies
    url: /policies/[full_slug]/
    icon: wysiwyg
    _enabled_editors:
      - content

_inputs:
  block:
    hidden: true
  src:
    type: image
    options:
      accepts_mime_types: "image/jpeg,image/jpg,image/png,image/webp"
      mime_type: image/webp
      resize_style: contain
      width: 1920
      height: 1920
  href:
    type: url
  rating:
    type: range
    options:
      min: 0
      max: 5
      step: 0.5
  paragraph:
    type: textarea
  content:
    type: html
