lang: nl
company: Lorem Ipsum
header:
  block: header-1
  text: Ank Schravendeel
  menus:
    - text: Home
      href: /
    - text: Coaching
      href: /coaching/
    - text: Meditatie
      links:
        - text: Meditatie
          href: /meditatie/
        - text: Retraite
          href: /retraite/
        - text: Zingend mediteren
          href: /zingend-mediteren/
    - text: Agenda
      href: /agenda/
    - text: Lezingen
      href: /lezingen/
    - text: Blog
      href: /blogs/
    - text: Over mij
      href: /over-mij/
  buttons:
    - text: Neem contact op
      href: /contact/
footer:
  block: footer-1
  logo:
    src: /images/placeholder.webp
  menus:
    - text: Contact
      href: /contact/
      links:
        - text: Email
          href: mailto:info@example.com
        - text: Phone
          href: tel:+1234567890
    - text: Legal
      links:
        - text: Privacy
          href: /privacy/
        - text: Terms
          href: /terms/
head: ""
body: ""
css: ""
