lang: nl
company: Lorem Ipsum
banner:
  variant: 1
header:
  variant: 1
  search: false
  class: dark
  logo:
    src: /images/placeholder.webp
    alt: Logo Lorem
  menus:
    - text: Home
      href: /
    - text: Coaching
      href: /coaching/
    - text: Meditatie
      links:
        - text: Retraite
          href: /retraite/
        - text: Meditatie
          href: /meditatie/
        - text: Zingend mediteren
          href: /zingend-mediteren/
    - text: Agenda
      href: /agenda/
    - text: Over mij
      href: /over-mij/
  buttons:
    - text: Neem contact op
      href: /contact/
footer:
  variant: 1
  class: dark
  logo:
    src: /images/placeholder.webp
    alt: Logo Lorem
  menus:
    - text: Contact
      href: /contact/
      links:
        - text: Email
          href: mailto:info@example.com
        - text: Phone
          href: tel:+1234567890
    - text: Legal
      links:
        - text: Privacy
          href: /privacy/
        - text: Terms
          href: /terms/
head: ""
body: ""
css: ""
